### ISSUE TITLE
TypeError: i is not iterable in spector.bundle.js

### ISSUE THREAD

**Issue by ennemli** [BabylonJS/Spector.js#303]
While debugging the canvas using SpectorJS, a **TypeError** was encountered. The error message “**i is not iterable**” suggests that there was an attempt to iterate over a value that is not iterable. I'm not sure but it seems This error occurred in the spector.js file.

I also tried to debug [here](https://spector.babylonjs.com/demos/pbr/)
I got the same error

error:

```
TypeError: i is not iterable
    at $e.getProgramData (spector.bundle.js:1:552108)
    at Pe.readFromContext (spector.bundle.js:1:553662)
    at Pe.readFromContextNoSideEffects (spector.bundle.js:1:524320)
    at Pe.onConsumeCommand (spector.bundle.js:1:522203)
    at ke.captureState (spector.bundle.js:1:567736)
    at qe.onCommand (spector.bundle.js:1:588557)
    at WebGL2RenderingContext.drawElements (spector.bundle.js:1:519529)
    at Engine.draw (babylon.new.js:9022:26)
    at Mesh._draw (babylon.new.js:21147:36)
    at Mesh._processRendering (babylon.new.js:21275:30) []
```

**Comment by sebavan** [comment]
Which browser is it happening in ?

I can not repro locally :-(

**Comment by ennemli** [comment]
> Which browser is it happening in ?
> 
> I can not repro locally :-(

I didn't try any other browser other than Brave

**Comment by ennemli** [comment]
In MS Edge, things worked perfectly.

**Comment by sebavan** [comment]
This would mean that somehow this fails:
![image](https://github.com/BabylonJS/Spector.js/assets/16655165/5fe47ae3-5860-41dd-9979-d1cd91477d39)

but only on brave which is really strange :-(

**Comment by mbkv** [comment]
https://github.com/brave/brave-browser/issues/37044

can confirm it's a bug with brave browser. guess gotta use firefox for development

**Comment by sebavan** [comment]
Thanks for the confirmation
