### ISSUE TITLE
SpectorJS broken in Chrome Canary due to new, lower postMessage size limit

### ISSUE THREAD

**Issue by kenrussell** [BabylonJS/Spector.js#69]
Chrome version: 63.0.3236.0 (Official Build) canary (64-bit) 
OS: macOS 10.12.6 on Retina MacBook Pro, NVIDIA GPU

To reproduce :

1) Load https://webglsamples.org/aquarium/aquarium.html
2) Record a frame from the canvas via Spector.js
3) The record will fail to display.
4) Open the console

It contains:
<pre>
Uncaught Error: Message length exceeded maximum allowed length.
    at PortImpl.postMessage (extensions::messaging:121:13)
    at Port.publicClassPrototype.(anonymous function) [as postMessage] (extensions::utils:138:26)
    at Object.sendMessageImpl (extensions::messaging:399:12)
    at Object.<anonymous> (extensions::runtime:57:15)
    at Object.handleRequest (extensions::binding:64:27)
    at Object.<anonymous> (extensions::binding:374:32)
    at sendMessage (chrome-extension://denbgaamihkadbghdceggmchnflmhpmk/contentScript.js:18:28)
    at HTMLDocument.<anonymous> (chrome-extension://denbgaamihkadbghdceggmchnflmhpmk/contentScript.js:206:9)
</pre>

**Comment by kenrussell** [comment]
CC'ing @fserb .

**Comment by sebavan** [comment]
Hello @kenrussell 

Thank for the feedback. Are you aware of anything I could/should use in Canary to share a huge amount of data with an extension ? 

Also What is the current limit ?

I will fix it as soon as we agree on the best strategy for this. I hope I won t have to split the capture to make the extension work.

Thx

**Comment by NuclearCookie** [comment]
if you find a different way to send data to extensions, it might help with https://github.com/BabylonJS/Spector.js/pull/63

**Comment by NuclearCookie** [comment]
I just stumbled upon this: https://github.com/krakenjs/post-robot Do you think this could fix the issue?

**Comment by sebavan** [comment]
I ll have a look at it, thx. I will wait the answer to this issue before integrating #63 .

**Comment by kenrussell** [comment]
Happy to report that I found a small and localized fix for this problem. :)

**Comment by deltakosh** [comment]
Thanks! Much appreciated ;)

**Comment by kenrussell** [comment]
You're welcome, happy to contribute :)
